### PR TITLE
Redeemer : call redeemDaoBounty only if pstate is Executed.

### LINKED ISSUE #643: Redeemer.redeem fails in proposals that are expiredinQueue
If the propsal state is `expiredInQueue`, the redeemer contracts `redeem()`  [will call genesisProtocol.redeemDaoBounty](https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L70).

However, `genesisProtocol.redeemDaoBounty` requires that the proposal be in the `Executed` state: https://github.com/daostack/infra/blob/master/contracts/votingMachines/GenesisProtocolLogic.sol#L401

And so the transaction will fail.

### PR DESCRIPTION
**Pull request by orenyodfat**
fix #643

### CODE REVIEW

File: test/contributionreward.js [hunk 1]
```diff
@@ -601,6 +601,35 @@ contract('ContributionReward', accounts => {
...
+                                                                      testSetup.standardTokenMock.address,
+                                                                      otherAvatar.address
+                                                                    );
+       var proposalId = await helpers.getValueFromLogs(tx, '_proposalId',1);
+
+       await testSetup.contributionRewardParams.votingMachine.genesisProtocol.vote(proposalId,1,0,helpers.NULL_ADDRESS,{from:accounts[1]});
+       await helpers.increaseTime(60+1);
+       var arcUtils = await Redeemer.new(testSetup.contributionReward.address,testSetup.contributionRewardParams.votingMachine.genesisProtocol.address);
+       var proposal = await testSetup.contributionRewardParams.votingMachine.genesisProtocol.proposals(proposalId);
+       assert.equal(proposal.state,3); //ExpiredInQueue
```
Comment (jellegerbrandy) [inline test/contributionreward.js]: state 3 is `Queued`, i think?
